---

- name: python2 packages
  apt:
    pkg: "{{ item }}"
    state: present
  become: true
  with_items: "{{ apt_packages }}"
  tags:
    - python

- name: user pip packages
  become: true
  command: /usr/bin/pip2 install "{{ item }}"
  with_items: "{{ python2_packages }}"
  tags:
    - python

- name: install python2 ipykernel
  command: python2 -m ipykernel install
